apiVersion: v1
kind: ReplicationController
metadata:
  name: iduploadservice-rc
  labels:
    app: iduploadservice
    zone: testing
    version: v1
spec:
  replicas: 2
  selector:
    app: iduploadservice
    zone: testing
    version: v1
  template:
    metadata:
      labels:
        app: iduploadservice
        zone: testing
        version: v1
    spec:
      containers:
        - name: iduploadservice
          image: hmallah/iduploadservice:latest
          ports:
            - name: replyport
              hostPort: 5000
              containerPort: 5000
      imagePullSecrets:
        - name: repositorySecretKey
